#!/usr/bin/env node
/* Writes each route's title, description, canonical URL and robots rule into nginx.conf, from the
 * frontend's assets/js/seo.js.
 *
 * Every route is served the same index.html, and seo.js only retitles the page once its script
 * runs. Google runs it; a link preview does not -- Discord, X, WhatsApp and the rest read the HTML
 * as served and stop. A link to /discord therefore previewed as the home page. nginx now swaps the
 * home page's values for the route's own in the HTML on the way out (sub_filter, keyed on these
 * maps), so the preview, the tab and the search result all say the same thing.
 *
 *   node infra/nginx/seo-map.mjs           rewrite the two generated blocks in nginx.conf
 *   node infra/nginx/seo-map.mjs --check   exit 1 if they are out of date
 *
 * services/api-gateway/tests/seo.test.ts runs the same check.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const repo = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
export const NGINX_CONF = path.join(repo, 'infra/nginx/nginx.conf');
export const SEO_JS = path.join(repo, 'DONUTDROP FRONTEND/Donut Drop/assets/js/seo.js');

const MAPS_BEGIN = '  # ── seo maps: generated by infra/nginx/seo-map.mjs from seo.js, do not edit by hand ──';
const MAPS_END = '  # ── end seo maps ──';
const SUBS_BEGIN = '      # ── seo substitutions: generated by infra/nginx/seo-map.mjs, do not edit by hand ──';
const SUBS_END = '      # ── end seo substitutions ──';

/** As the text appears inside index.html's attributes and <title>. */
export function htmlText(text) {
  return text
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function quoted(text) {
  // Nothing here may end a string or start a variable in nginx's grammar.
  if (/["'\\$]/.test(text)) throw new Error(`cannot put ${JSON.stringify(text)} in nginx.conf`);
  return `"${text}"`;
}

/** The URL paths a route answers on. Home is also /home; Rewards still answers its old name. */
function pathsFor(route) {
  if (route === 'home') return ['/home'];
  if (route === 'rewards') return ['/rewards', '/rakeback'];
  return [`/${route}`];
}

/** The strings in the served home page that each route's own value replaces. */
export function homeStrings(seo) {
  const home = seo.ROUTE_META.home;
  return {
    title: htmlText(home.title),
    description: htmlText(home.description),
    canonical: `<link rel="canonical" href="${seo.canonicalUrl('home')}" />`,
    ogUrl: `<meta property="og:url" content="${seo.canonicalUrl('home')}" />`,
    robots: '<meta name="robots" content="index, follow" />',
  };
}

export function renderMaps(seo) {
  const routes = Object.keys(seo.ROUTE_META);
  /* Keyed on $seo_path, not $uri. The page routes serve index.html through try_files, and a
   * try_files that finds its file rewrites $uri to that file -- so by the time sub_filter asks,
   * $uri is "/index.html" for every route and every map answered with the home page's values.
   * $seo_path is set from $uri in the rewrite phase, before try_files runs. */
  const map = (variable, value) =>
    [
      `  map $seo_path ${variable} {`,
      `    default ${quoted(value('home'))};`,
      ...routes.flatMap((route) => pathsFor(route).map((p) => `    ${p} ${quoted(value(route))};`)),
      '  }',
    ].join('\n');
  return [
    MAPS_BEGIN,
    map('$seo_title', (route) => htmlText(seo.ROUTE_META[route].title)),
    map('$seo_description', (route) => htmlText(seo.ROUTE_META[route].description)),
    map('$seo_url', (route) => seo.canonicalUrl(route)),
    map('$seo_robots', (route) => (seo.PRIVATE_ROUTES.has(route) ? 'noindex, follow' : 'index, follow')),
    MAPS_END,
  ].join('\n');
}

export function renderSubstitutions(seo) {
  const home = homeStrings(seo);
  const sub = (from, to) => {
    if (from.includes("'") || to.includes("'")) throw new Error('a quote would end the string');
    return `      sub_filter '${from}' '${to}';`;
  };
  return [
    SUBS_BEGIN,
    // The path as requested, captured before try_files rewrites $uri to /index.html.
    '      set $seo_path $uri;',
    '      sub_filter_once off;',
    sub(home.title, '$seo_title'),
    sub(home.description, '$seo_description'),
    sub(home.canonical, '<link rel="canonical" href="$seo_url" />'),
    sub(home.ogUrl, '<meta property="og:url" content="$seo_url" />'),
    sub(home.robots, '<meta name="robots" content="$seo_robots" />'),
    SUBS_END,
  ].join('\n');
}

function replaceBetween(text, begin, end, block) {
  const start = text.indexOf(begin);
  const stop = text.indexOf(end, start);
  if (start < 0 || stop < 0) throw new Error(`nginx.conf is missing the markers ${begin.trim()}`);
  return text.slice(0, start) + block + text.slice(stop + end.length);
}

/** nginx.conf as it should read, line endings normalised to \n. */
export function expectedConf(conf, seo) {
  let next = conf.replace(/\r\n/g, '\n');
  next = replaceBetween(next, MAPS_BEGIN, MAPS_END, renderMaps(seo));
  next = replaceBetween(next, SUBS_BEGIN, SUBS_END, renderSubstitutions(seo));
  return next;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const seo = await import(pathToFileURL(SEO_JS).href);
  const raw = readFileSync(NGINX_CONF, 'utf8');
  const eol = raw.includes('\r\n') ? '\r\n' : '\n';
  const current = raw.replace(/\r\n/g, '\n');
  const next = expectedConf(raw, seo);
  if (process.argv.includes('--check')) {
    if (next !== current) {
      console.error('nginx.conf is out of date with seo.js: run node infra/nginx/seo-map.mjs');
      process.exit(1);
    }
    console.log('nginx.conf matches seo.js');
  } else {
    writeFileSync(NGINX_CONF, next.replace(/\n/g, eol));
    console.log(next === current ? 'nginx.conf already up to date' : 'nginx.conf updated');
  }
}
