BEGIN;

-- The ledger gets an order that two rows from the same transaction cannot share.
--
-- `created_at` defaults to now(), which in Postgres is TRANSACTION-start time, not statement time.
-- A settled round writes two rows in one transaction — the win credit and the stake debit — so both
-- carry the identical timestamp, and every reader ordering by `created_at DESC, id DESC` was
-- tie-breaking on a random uuid. Which row counted as newest was a coin flip, per round.
--
-- That already cost a live bug: the deposit poll corrected the wallet pill from the newest row and
-- landed on the credit half, reporting the balance before the stake came out. It is fenced in the
-- client now, but the history view still lists a win above its own stake half the time, and every
-- future reader of this table would have inherited the same trap.
--
-- An identity column is monotonic within and across transactions, so it separates rows that share a
-- timestamp and needs no separate sequence grant: the permission rides on the table, which is one
-- fewer thing to forget when a new role appears.
ALTER TABLE wallet_transactions ADD COLUMN seq bigint;

-- Backfilling recovers the real order rather than freezing the arbitrary one.
--
-- The balances themselves say what happened: the rows of one transaction form a chain, where each
-- row's closing balance is the next row's opening balance. So a row whose opening balance
-- (balance_after_minor - amount_minor) equals a sibling's closing balance is the one that came
-- SECOND, and ordering on that puts the chain back together.
--
-- It is exact for a pair, which is every ambiguous group this table currently holds. A longer chain
-- would only be partially recovered, and falls back to id order — no worse than the coin flip it
-- replaces, and there are none here to worry about.
-- The chain test is computed in its own step rather than inline in the window's ORDER BY, so the
-- statement uses nothing more exotic than a scalar subquery in a SELECT list.
WITH keyed AS (
  SELECT w.id,
         w.created_at,
         (SELECT count(*)
            FROM wallet_transactions sibling
           WHERE sibling.user_id = w.user_id
             AND sibling.created_at = w.created_at
             AND sibling.id <> w.id
             AND sibling.balance_after_minor = w.balance_after_minor - w.amount_minor)
           AS continues_a_sibling
    FROM wallet_transactions w
),
ordered AS (
  SELECT id,
         row_number() OVER (ORDER BY created_at, continues_a_sibling, id) AS position
    FROM keyed
)
UPDATE wallet_transactions target
   SET seq = ordered.position
  FROM ordered
 WHERE ordered.id = target.id;

ALTER TABLE wallet_transactions ALTER COLUMN seq SET NOT NULL;
ALTER TABLE wallet_transactions ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY;

-- The identity's own sequence starts after everything the backfill assigned, or the first insert
-- collides with row one.
SELECT setval(
  pg_get_serial_sequence('wallet_transactions', 'seq'),
  COALESCE((SELECT max(seq) FROM wallet_transactions), 0) + 1,
  false
);

ALTER TABLE wallet_transactions ADD CONSTRAINT wallet_transactions_seq_key UNIQUE (seq);
-- The shape every reader of this table uses: one account's ledger, newest first.
CREATE INDEX wallet_transactions_user_seq_idx ON wallet_transactions (user_id, seq DESC);

-- Supersedes donut_schema_ready_v30. The readiness probe names the exact schema the running API
-- expects, so traffic cannot reach a history query that orders by a column which does not exist.
CREATE FUNCTION donut_schema_ready_v31() RETURNS boolean
  LANGUAGE sql
  IMMUTABLE
  PARALLEL SAFE
  SET search_path = pg_catalog, public
  AS $$ SELECT true $$;

REVOKE ALL ON FUNCTION donut_schema_ready_v31() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION donut_schema_ready_v31() TO donut_api_runtime;

COMMIT;
