BEGIN;

-- The ledger gets an order that two rows from the same transaction cannot share.
--
-- `created_at` defaults to now(), which in Postgres is TRANSACTION-start time, not statement time.
-- A settled round writes two rows in one transaction — the win credit and the stake debit — so both
-- carry the identical timestamp, and every reader ordering by `created_at DESC, id DESC` was
-- tie-breaking on a random uuid. Which row counted as newest was a coin flip, per round.
--
-- That already cost a live bug: the deposit poll corrected the wallet pill from the newest row and
-- landed on the credit half, reporting the balance before the stake came out. It is fenced in the
-- client now, but the history view still lists a win above its own stake half the time, and every
-- future reader of this table would have inherited the same trap.
--
-- ── WHY THERE IS NO BACKFILL ──
--
-- The first version of this migration added the column and then UPDATEd every existing row to put
-- the historical order back together. It applied cleanly in CI, whose database is empty at this
-- point in the ladder, and failed on the production database with
--
--     error: wallet_transactions is append-only
--
-- raised by the reject_mutation() trigger migration 008 puts on this table.
--
-- That trigger is the reason the ledger is worth anything. A balance is auditable only because the
-- rows behind it can never be rewritten, and a migration is not an exception to that — a
-- privileged process quietly rewriting ledger history is precisely what the rule exists to stop.
-- Disabling the trigger to get the backfill through would have been the worst available version of
-- this change: it would have worked, and it would have spent the guarantee to tidy a sort order.
--
-- So nothing is updated. One ADD COLUMN carrying an identity fills the existing rows as part of the
-- table rewrite, which is DDL: every row receives a value without an UPDATE being issued, so no
-- row-level trigger fires and no ledger row is mutated in the sense the trigger means.
--
-- The values existing rows receive follow the physical order of the heap. For a table that has only
-- ever been appended to that is its insertion order, so the historical ordering comes out right in
-- practice — but that is a property of how this table has been used, not a guarantee of the
-- standard, and it is not worth rewriting a ledger to improve on. What matters is that from here
-- every row carries an order nothing can tie.
--
-- Identity rather than a hand-rolled sequence: an identity's permission rides on the table, while a
-- standalone sequence needs its own USAGE grant, and forgetting that breaks every wallet write on
-- the platform.
ALTER TABLE wallet_transactions
  ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE wallet_transactions ADD CONSTRAINT wallet_transactions_seq_key UNIQUE (seq);
-- The shape every reader of this table uses: one account's ledger, newest first.
CREATE INDEX wallet_transactions_user_seq_idx ON wallet_transactions (user_id, seq DESC);

-- Belt and braces on the identity's sequence.
--
-- PostgreSQL documents an identity column's sequence as an implementation detail of the column:
-- unlike a `serial`, an inserting role is not supposed to need USAGE on it, so this should be
-- redundant. It is here anyway because of what being wrong would cost. Every credit and every debit
-- inserts into this table, so a missing sequence privilege would not degrade something — it would
-- stop the casino taking a single wager, while the readiness probe kept answering healthy because
-- it only reads.
DO $grant$
DECLARE
  sequence_name text := pg_get_serial_sequence('wallet_transactions', 'seq');
BEGIN
  IF sequence_name IS NOT NULL THEN
    EXECUTE format('GRANT USAGE, SELECT ON SEQUENCE %s TO donut_api_runtime', sequence_name);
  END IF;
END
$grant$;

-- Supersedes donut_schema_ready_v30. The readiness probe names the exact schema the running API
-- expects, so traffic cannot reach a history query that orders by a column which does not exist.
CREATE FUNCTION donut_schema_ready_v31() RETURNS boolean
  LANGUAGE sql
  IMMUTABLE
  PARALLEL SAFE
  SET search_path = pg_catalog, public
  AS $$ SELECT true $$;

REVOKE ALL ON FUNCTION donut_schema_ready_v31() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION donut_schema_ready_v31() TO donut_api_runtime;

COMMIT;
